# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [2]:
import torch

Construct a 5x3 matrix, uninitialized

In [4]:
x = torch.Tensor(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 6.5204e-39],
        [4.6837e-39, 8.4489e-39, 9.6428e-39],
        [1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39],
        [9.2755e-39, 9.1837e-39, 9.3674e-39]])


Construct a randomly initialized matrix

In [70]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3654, 0.5352, 0.0784],
        [0.3948, 0.3778, 0.2657],
        [0.2429, 0.6744, 0.4957],
        [0.0033, 0.8272, 0.1987],
        [0.0820, 0.9065, 0.0700]])


Get its size

In [71]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [72]:
x[1:3] = 2
print(x)

tensor([[0.3654, 0.5352, 0.0784],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.0033, 0.8272, 0.1987],
        [0.0820, 0.9065, 0.0700]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

#### 1st Make a tensor of size (2,17)

In [73]:
A = torch.Tensor(2,17)
A, A.type()
# If we create a tensor it initialize it with flat numbers 


(tensor([[9.2755e-39, 1.0561e-38, 9.4592e-39, 4.6837e-39, 8.4489e-39, 1.0102e-38,
          9.0919e-39, 1.0102e-38, 8.9082e-39, 8.4489e-39, 9.6429e-39, 8.4490e-39,
          9.6429e-39, 9.2755e-39, 1.0286e-38, 9.0919e-39, 8.9082e-39],
         [9.2755e-39, 8.4490e-39, 9.2755e-39, 1.0745e-38, 1.0286e-38, 8.4490e-39,
          1.0837e-38, 1.0102e-38, 1.0194e-38, 9.2755e-39, 8.4490e-39, 1.1112e-38,
          9.2755e-39, 9.1837e-39, 8.7245e-39, 1.1112e-38, 9.2755e-39]]),
 'torch.FloatTensor')

#### Make a torch.FloatTensor of size (3, 1)

In [74]:
# We can directly create a Float Tensor with:
B = torch.FloatTensor(3, 1)
B, B.type()

(tensor([[1.4013e-45],
         [0.0000e+00],
         [0.0000e+00]]),
 'torch.FloatTensor')

In [75]:
# We can also initialize a zero tensor and specify it to be a Float Tensor 
B1 = torch.zeros([3,1], dtype=torch.float64)
B1, B1.type()

(tensor([[0.],
         [0.],
         [0.]], dtype=torch.float64),
 'torch.DoubleTensor')

#### 3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s

LongTensor it's just a tensor with large integers. 

In [76]:
C = torch.LongTensor(5,2,1)
C

tensor([[[8030883942554935410],
         [6069846680300760690]],

        [[2336920844425046078],
         [7142831553556196163]],

        [[6998721855611104879],
         [8367808407074058272]],

        [[8031079711376633445],
         [7305521896674582816]],

        [[  27584977221714034],
         [  31525394966315008]]])

In [77]:
C[:]=7
C

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])

#### Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]
Byte tensor comes from the unit byte, equivalent to use uint8 

In [78]:
D = torch.ByteTensor(5,)
D

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)

In [79]:
D[1:4] = 1
D

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [80]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.5553, 0.9484, 0.2742],
        [2.1019, 2.3071, 2.8061],
        [2.7631, 2.4846, 2.9224],
        [0.4232, 1.1665, 0.3919],
        [1.0539, 1.0511, 0.9173]])


### 2.2 Addition: syntax 2

In [105]:
print(torch.add(x, y))

tensor([[0.5553, 0.9484, 0.2742],
        [2.1019, 2.3071, 2.8061],
        [2.7631, 2.4846, 2.9224],
        [0.4232, 1.1665, 0.3919],
        [1.0539, 1.0511, 0.9173]])


### 2.3 Addition: giving an output tensor

In [107]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


tensor([[0.5553, 0.9484, 0.2742],
        [2.1019, 2.3071, 2.8061],
        [2.7631, 2.4846, 2.9224],
        [0.4232, 1.1665, 0.3919],
        [1.0539, 1.0511, 0.9173]])


### 2.4 Addition: in-place

adds `x`to `y`

In [108]:
y.add_(x)
print(y)

tensor([[0.5553, 0.9484, 0.2742],
        [2.1019, 2.3071, 2.8061],
        [2.7631, 2.4846, 2.9224],
        [0.4232, 1.1665, 0.3919],
        [1.0539, 1.0511, 0.9173]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [109]:
print(x[:, 1])

tensor([0.5352, 2.0000, 2.0000, 0.8272, 0.9065])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

#### 1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))

In [115]:
x = torch.zeros([2,2]) + 5
x[1,:] = 10
y = torch.zeros([2,2]) + 2
x, y

(tensor([[ 5.,  5.],
         [10., 10.]]),
 tensor([[2., 2.],
         [2., 2.]]))

In [116]:
print(x*y)

tensor([[10., 10.],
        [20., 20.]])

#### 2. do the same, but inplace

#### 3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))

4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [ ]:
a = torch.ones(5)
print(a)

In [ ]:
b = a.numpy()
print(b)

See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [ ]:
a.add_(1)
print(a)
print(b)

### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [63]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
